In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Parameter Management

In [2]:
import torch
from torch import nn

In [3]:
# 具有一个隐藏层的 MLP
net = nn.Sequential(nn.LazyLinear(8),  # 第一个线性层，将输入映射到8个输出单元 (隐藏层)
                    nn.ReLU(),  # 激活函数
                    nn.LazyLinear(1))  # 第二个线性层，将8个输入映射到1个输出单元

X = torch.rand(size=(2, 4))
net(X).shape

torch.Size([2, 1])

In [4]:
net[2].state_dict()  # 通过索引获得权重参数

OrderedDict([('weight',
              tensor([[-0.1293, -0.1664,  0.1976, -0.2060, -0.2076, -0.2265,  0.2052,  0.1212]])),
             ('bias', tensor([0.0153]))])

In [5]:
X

tensor([[0.5922, 0.6869, 0.4482, 0.1364],
        [0.2770, 0.1608, 0.4327, 0.7418]])

In [6]:
type(net[2].bias), net[2].bias.data

(torch.nn.parameter.Parameter, tensor([0.0153]))

In [7]:
[(name, param.shape) for name, param in net.named_parameters()]

[('0.weight', torch.Size([8, 4])),
 ('0.bias', torch.Size([8])),
 ('2.weight', torch.Size([1, 8])),
 ('2.bias', torch.Size([1]))]

In [8]:
# We need to give the shared layer a name so that we can refer to its
# parameters
shared = nn.LazyLinear(8)
net = nn.Sequential(nn.LazyLinear(8), nn.ReLU(),
                    shared, nn.ReLU(),
                    shared, nn.ReLU(),
                    nn.LazyLinear(1))

net(X)
# Check whether the parameters are the same
print(net[2].weight.data[0] == net[4].weight.data[0])
net[2].weight.data[0, 0] = 100
# Make sure that they are actually the same object rather than just having the
# same value
print(net[2].weight.data[0] == net[4].weight.data[0])

tensor([True, True, True, True, True, True, True, True])
tensor([True, True, True, True, True, True, True, True])
